on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Installing Az CLI 
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -q --upgrade --pre azure-cli
         az --version
      

        # Checkout code
      - name: Check out repository  
        uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureChina'

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azuredeploy.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
